# Generated by Django 3.1.3 on 2020-11-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201114_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
