# Generated by Django 3.1.3 on 2020-11-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201114_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtickets',
            name='movie_date',
            field=models.CharField(max_length=150),
        ),
    ]
