# Generated by Django 3.1.3 on 2020-11-14 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_auto_20201114_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='username',
        ),
        migrations.AddField(
            model_name='ticket',
            name='movie_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BookingTickets',
        ),
    ]
