# Generated by Django 3.1.3 on 2020-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20201114_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.CharField(blank=True, choices=[('1', '13:00'), ('2', '14:00'), ('3', '15:00')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
