# Generated by Django 3.1.3 on 2020-11-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20201114_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=2, null=True)),
                ('movie', models.CharField(choices=[('1', 'movie-one'), ('2', 'movie-two'), ('3', 'movie-three')], max_length=9)),
            ],
        ),
    ]
