# Generated by Django 3.1.3 on 2020-11-14 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='seat',
            name='time',
            field=models.CharField(blank=True, choices=[('1', '13:00'), ('2', '14:00'), ('3', '15:00')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.seat'),
        ),
    ]
