# Generated by Django 3.1.3 on 2020-11-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20201114_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='time',
            field=models.CharField(blank=True, choices=[('13:00', '13:00'), ('18:00', '18:00')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.CharField(blank=True, choices=[('13:00', '13:00'), ('18:00', '18:00')], max_length=10, null=True),
        ),
    ]
