# Generated by Django 3.1.3 on 2020-11-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20201114_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
