# Generated by Django 3.1.3 on 2020-11-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20201116_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='chosen_movie',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='movie',
            field=models.CharField(choices=[('1', 'Black Panther'), ('2', 'Moonlight'), ('3', 'Aladdin')], max_length=9),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.CharField(choices=[('1', 'Black Panther'), ('2', 'Moonlight'), ('3', 'Aladdin')], max_length=9),
        ),
    ]
