# Generated by Django 3.1.3 on 2020-11-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_remove_seat_chosen_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='chosen_movie',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
